INSERT INTO TBL_CLIENT (ID, NAME, BALANCE) VALUES (0, 'Gabriel', 12200);
INSERT INTO TBL_CLIENT (ID, NAME, BALANCE) VALUES (1, 'Guilherme', 25000);
INSERT INTO TBL_CLIENT (ID, NAME, BALANCE) VALUES (2, 'Henrique', 35200);