INSERT INTO TBL_CLIENT ( NAME, BALANCE) VALUES ('Gabriel', 12200);
INSERT INTO TBL_CLIENT ( NAME, BALANCE) VALUES ('Guilherme', 25000);
INSERT INTO TBL_CLIENT ( NAME, BALANCE) VALUES ('Henrique', 35200);